global:
  dockerRegistrySecret: "" # leave empty if public repo
  baseRepo: "quay.io/ibm-dlf"
  arch: "amd64"
  type: "k8s"
  namespaceYaml: false

  sidecars:
    kubeletPath: "/var/lib/kubelet"
    baseRepo: "quay.io/k8scsi"
    images:
      externalAttacher:
        image: "csi-attacher"
        tag: "v2.2.0"
      nodeDriverRegistrar:
        image: "csi-node-driver-registrar"
        tag: "v1.2.0"
      externalProvisioner:
        image: "csi-provisioner"
        tag: "v2.0.2"

csi-s3-chart:
# baseRepo: "anotherrepo"
# dockerRegistrySecret: "anothersecret"
# mounter: "goofys"
  csis3:
    image: "csi-s3"
    tag: "latest"
  sidecars: {} # in case you want to force override regardless of the csi-s3-chart/values.yaml

csi-nfs-chart:
# baseRepo: "anotherrepo"
# dockerRegistrySecret: "anothersecret"
  csinfs:
    image: "csi-nfs"
    tag: "latest"
  sidecars: {} # in case you want to force override regardless of the csi-nfs-chart/values.yaml

dataset-operator-chart:
# baseRepo: "anotherrepo"
# dockerRegistrySecret: "anothersecret"
  generatekeys:
    image: "generate-keys"
    tag: "latest"
  datasetoperator:
    image: "dataset-operator"
    tag: "label-edit"

unrestricted: false
